name:                udp2tcp
version:             0.1.0.0
github:              "githubuser/udp2tcp"
license:             BSD3
author:              "sergius"
maintainer:          "telegatrollej@yandex.ru"
copyright:           "2019 sergius"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/udp2tcp#readme>

dependencies:
- base >= 4.7 && < 5
- network
- process
- bytestring

library:
  source-dirs: src

executables:
  udp2tcp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fPIC
    dependencies:
    - udp2tcp
    ld-options: 
    - -static

tests:
  udp2tcp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - udp2tcp
